version: '3.8'

services:
    
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - rabbitmq
    ports:
      - '3000:8081'


  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"       # Porta padrão do RabbitMQ
      - "15672:15672"     # Interface de gerenciamento
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin123
    restart: always


volumes:
  mysql_data: